site_name: Chez-RtMidi
site_author: Gene Z. Ragan
repo_url: https://github.com/outcue/chez-rtmdidi

nav:
    - 'Getting Started': index.md
    - 'Overview of RtMidi': sdl.md
    - Tutorials:
      - 'Handling Events':          'tuts/events.md'
      - 'Renderer Basics':          'tuts/renderer.md'
      - 'Renderer Techniques':      'tuts/advanced-renderer.md'
      - 'Complete Example: Tetris': 'tuts/tetris.md'

    - Reference:
      - 'Basics':           'ref/basics.md'
      - 'Video':            'ref/video.md'
      - 'Audio':            'ref/audio.md'
      - 'Events':           'ref/events.md'
      - 'Inputs':           'ref/inputs.md'
      - 'Force Feedback':   'ref/force.md'
      - 'Power Management': 'ref/power.md'
      - 'Timers':           'ref/timers.md'
      - 'Values':           'ref/values.md'
      - 'Data Objects':     'ref/data.md'

theme: readthedocs

copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
